services:
  evolution-api:
    image: atendai/evolution-api:v1.8.7
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - evolution_data:/evolution/instances
      - evolution_store:/evolution/store
    environment:
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=salon2024
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - LANGUAGE=pt-BR
      - DEL_INSTANCE=false

volumes:
  evolution_data:
  evolution_store:
